[package]
name = "oribos_lang"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
pest = "2.0"
pest_derive = "2.0"
dyn-clone = "1.0.11"
mimalloc = { version = "0.1.17", default-features = false }

[profile.release]
lto = "fat"
codegen-units = 1